# Generated by Django 6.0.2 on 2026-02-22 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('dev', 'Web Development'), ('apt', 'Aptitude & Logic'), ('soft', 'Soft Skills'), ('ast', 'Astronomy')], max_length=20)),
                ('external_link', models.URLField(blank=True, help_text='Link to YouTube, LeetCode, etc.')),
                ('estimated_time', models.IntegerField(help_text='Time in minutes')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_interest', models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('dev', 'Web Development'), ('apt', 'Aptitude & Logic'), ('soft', 'Soft Skills'), ('ast', 'Astronomy')], default='dsa', max_length=20)),
                ('target_career', models.CharField(help_text='e.g. System Analyst, Web Developer', max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
