# Generated by Django 6.0.2 on 2026-02-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_timeslot_options_alter_timetableentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=3),
        ),
    ]
