# Generated by Django 6.0.2 on 2026-02-22 12:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('timetable', '0003_alter_timetableentry_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timetable_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to='timetable.timetableentry'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'timetable_entry', 'date')},
        ),
    ]
