# Generated by Django 6.0.2 on 2026-02-22 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_attendance_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='entry_method',
            field=models.CharField(choices=[('qr', 'QR Scan'), ('manual', 'Manual Entry')], default='qr', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_attendance_marks', to=settings.AUTH_USER_MODEL),
        ),
    ]
